version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["flask", "run", "--host=0.0.0.0"]
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: FLASK_QUESTIONS
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

    depends_on:
      - db